"""
YOLOv12 Confusion Matrix Calculator
====================================

This script computes a confusion matrix from YOLOv12 annotation files.

YOLO Annotation Format:
    Each line: class_id x_center y_center width height
    All coordinates are normalized (0-1)

Usage:
    python yolo_confusion_matrix.py

Then modify the paths in the main section:
    ground_truth_dir = "path/to/ground_truth"
    predictions_dir = "path/to/predictions"

Confusion Matrix Components:
    - TP (True Positive): Predicted box matches ground truth box (IoU >= threshold)
    - FP (False Positive): Predicted box with no matching ground truth
    - FN (False Negative): Ground truth box with no matching prediction
    - TN (True Negative): Images with no objects in both GT and predictions
"""

from geopandas import GeoDataFrame
from dataclasses import dataclass
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

FONT_SIZE = 16

@dataclass
class ConfusionMatrix:
    tp: int = 0
    fp: int = 0
    fn: int = 0
    tn: int = 0


    @classmethod
    def fromFile(cls, file: Path):
        """
        This method loads file generated by the print function.
        """

        lines = []
        with open(file, "r") as f:
            lines = f.readlines()

        results = cls()
        results.tp = int(lines[0].split()[1])
        results.fp = int(lines[1].split()[1])
        results.fn = int(lines[2].split()[1])
        results.tn = int(lines[3].split()[1])

        return results


    @classmethod
    def fromDict(cls, dict):
        results = cls()

        results.tp = int(dict["TP"])
        results.fp = int(dict["FP"])
        results.fn = int(dict["FN"])
        results.tn = int(dict["TN"])

        return results


    def print(self, save: Path | str = ""):
        print("\n" + "="*50)
        print("CONFUSION MATRIX (Object Detection)")
        print("="*50)
        print("\n                            Actual")
        print("                         Positive  Negative")
        print(f"Predicted   Positive    {self.tp:6d}    {self.fp:6d}")
        print(f"            Negative    {self.fn:6d}    {self.tn:6d}")
        print("\n" + "="*50)

        precision = self.tp / (self.tp + self.fp) if (self.tp + self.fp) > 0 else 0
        recall = self.tp / (self.tp + self.fn) if (self.tp + self.fn) > 0 else 0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
        accuracy = (self.tp + self.tn) / (self.tp + self.tn + self.fp + self.fn) if (self.tp + self.tn + self.fp + self.fn) > 0 else 0

        print(f"\nMetrics:")
        print(f"  Accuracy:  {accuracy:.4f}")
        print(f"  F1-Score:  {f1:.4f}")
        print(f"  Precision: {precision:.4f}")
        print(f"  Recall:    {recall:.4f}")
        print("="*50 + "\n")

        if save != "":
            save = Path(save)
            save.parent.mkdir(parents=True, exist_ok=True)
            if save.exists():
                save = str(save).replace(".txt", "_new.txt")
            with open(save, "w") as f:
                f.write(f"TP: {self.tp}\n")
                f.write(f"FP: {self.fp}\n")
                f.write(f"FN: {self.fn}\n")
                f.write(f"TN: {self.tn}\n")
                f.write(f"Accuracy: {accuracy:.4f}\n")
                f.write(f"Precision: {precision:.4f}\n")
                f.write(f"F1-Score: {f1:.4f}\n")
                f.write(f"Recall: {recall:.4f}\n")


    def plot(self, save: Path | str, *, normalised: bool = False, hold: bool = True):

        matrix = np.array([[self.tp, self.fp],
                           [self.fn, self.tn]])
        if normalised:
            matrix = matrix.astype(np.float32)
            matrix_sum = matrix.sum()
            if matrix_sum > 0:
                matrix /= matrix_sum

        fmt = '.2g' if normalised else 'g'
        plt.figure(figsize=(7, 5))
        sns.heatmap(matrix,
            annot=True,
            fmt=fmt,
            cmap='Blues',
            xticklabels=['Positive', 'Negative'],
            yticklabels=['Positive', 'Negative'],
            annot_kws={"size": FONT_SIZE})

        plt.xlabel('Ground Truth', fontsize=FONT_SIZE)
        plt.tick_params(axis='x', labelsize=FONT_SIZE-1)

        plt.ylabel('Predictions', fontsize=FONT_SIZE)
        plt.tick_params(axis='y', labelsize=FONT_SIZE-1)

        plt.title(f"Confusion Matrix {'(Normalised)' if normalised else ''}", fontsize=FONT_SIZE)

        if save != "":
            save = Path(save)
            save.parent.mkdir(parents=True, exist_ok=True)
            if save.exists():
                save = str(save).replace(".png", "_new.png")
            plt.savefig(f"{save}")

        if not hold:
            plt.show()
            plt.close()



class Metrics:

    def __convert_obb_to_segmentation(self, obb):
        """Convert Oriented Bounding Box (OBB) to segmentation format."""
        x_center, y_center, width, height, angle = obb
        angle_rad = np.radians(angle)

        # Calculate the corners of the OBB
        cos_a = np.cos(angle_rad)
        sin_a = np.sin(angle_rad)

        dx = width / 2
        dy = height / 2

        corners = [
            x_center + cos_a * dx - sin_a * dy, y_center + sin_a * dx + cos_a * dy,  # top-right
            x_center - cos_a * dx - sin_a * dy, y_center - sin_a * dx + cos_a * dy,  # top-left
            x_center - cos_a * dx + sin_a * dy, y_center - sin_a * dx - cos_a * dy,  # bottom-left
            x_center + cos_a * dx + sin_a * dy, y_center + sin_a * dx - cos_a * dy   # bottom-right
        ]

        return corners

    def __parse_yolo_annotation(self, file_path):
        """Parse YOLOv12 annotation file and return list of bounding boxes."""
        boxes = []
        if not file_path or not Path(file_path).exists():
            return boxes

        with open(file_path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split()

                if len(parts) == 5:
                    x1, y1, x2, y2, x3, y3, x4, y4 = self.__convert_obb_to_segmentation(map(float, parts[1:5]))

                else:
                    x1, y1, x2, y2, x3, y3, x4, y4 = map(float, parts[1:])

                boxes.append((x1, y1, x2, y2, x3, y3, x4, y4))

        return boxes


    def __calculate_iou(self, box1, box2):
        """Calculate IoU between two boxes in YOLO format."""

        # In case the box is in format (x_center, y_center, width, height)
        if len(box1) == 4 and len(box2) == 4:
            x1, y1, w1, h1 = box1
            x2, y2, w2, h2 = box2

            # Convert to corner coordinates
            box1_x1, box1_y1 = x1 - w1/2, y1 - h1/2
            box1_x2, box1_y2 = x1 + w1/2, y1 + h1/2
            box2_x1, box2_y1 = x2 - w2/2, y2 - h2/2
            box2_x2, box2_y2 = x2 + w2/2, y2 + h2/2

        # In case the box is in format (x1, y1, x2, y2, x3, y3, x4, y4) - segmentation format
        else:
            xs = box1[0::2]  # x1, x3, x5, x7
            ys = box1[1::2]  # y1, y3, y5, y7
            box1_x1, box1_y1 = min(xs), min(ys)
            box1_x2, box1_y2 = max(xs), max(ys)

            xs = box2[0::2]
            ys = box2[1::2]
            box2_x1, box2_y1 = min(xs), min(ys)
            box2_x2, box2_y2 = max(xs), max(ys)

            w1 = box1_x2 - box1_x1
            h1 = box1_y2 - box1_y1

            w2 = box2_x2 - box2_x1
            h2 = box2_y2 - box2_y1

        # Calculate intersection
        inter_x1 = max(box1_x1, box2_x1)
        inter_y1 = max(box1_y1, box2_y1)
        inter_x2 = min(box1_x2, box2_x2)
        inter_y2 = min(box1_y2, box2_y2)

        if inter_x2 < inter_x1 or inter_y2 < inter_y1:
            # print(f"No intersection between boxes: {box1} vs {box2}")
            return 0.0

        intersection_area = (inter_x2 - inter_x1) * (inter_y2 - inter_y1)
        box1_area = w1 * h1
        box2_area = w2 * h2
        union_area = box1_area + box2_area - intersection_area

        iou = intersection_area / union_area if union_area > 0 else 0.0
        # print(f"Iou = overlap / union => {iou:.4f} = {inter_area:.4f} / {union_area:.4f}")

        return iou


    def __match_boxes(self, ground_truth_boxes, predicted_boxes, iou_threshold=0.5):
        """
        Match predicted boxes to ground truth using IoU threshold.
        """
        gt_matched = [False] * len(ground_truth_boxes)
        pred_matched = [False] * len(predicted_boxes)

        for pred_idx, pred_box in enumerate(predicted_boxes):
            best_iou = 0
            best_gt_idx = -1

            for gt_idx, gt_box in enumerate(ground_truth_boxes):
                # if gt_matched[gt_idx]:
                #     continue
                iou = self.__calculate_iou(pred_box, gt_box)

                if iou > best_iou:
                    best_iou = iou
                    best_gt_idx = gt_idx

            # print(f"Predicted box {pred_idx}: Best IoU = {best_iou:.4f} with GT box {best_gt_idx}")
            if best_iou >= iou_threshold and best_gt_idx >= 0:
                pred_matched[pred_idx] = True
                gt_matched[best_gt_idx] = True

        tp = sum(pred_matched)
        fp = len(predicted_boxes) - tp
        fn = len(ground_truth_boxes) - sum(gt_matched)

        return tp, fp, fn


    def compute_confusion_matrix(self, gt_dir, pred_dir, iou_threshold=0.5):
        """Compute confusion matrix from YOLO annotation directories."""
        gt_path = Path(gt_dir)
        pred_path = Path(pred_dir)

        total = ConfusionMatrix()

        gt_files = {f.stem: f for f in gt_path.glob('*.txt')}
        pred_files = {f.stem: f for f in pred_path.glob('*.txt')}
        all_images = set(gt_files.keys()).union(set(pred_files.keys()))

        for image_name in sorted(all_images):
            gt_boxes = self.__parse_yolo_annotation(gt_files.get(image_name))
            pred_boxes = self.__parse_yolo_annotation(pred_files.get(image_name))

            if len(gt_boxes) == 0 and len(pred_boxes) == 0:
                # total.tn += 1
                continue
            else:
                tp, fp, fn = self.__match_boxes(gt_boxes, pred_boxes, iou_threshold)
                total.tp += tp
                total.fp += fp
                total.fn += fn

        return total


    def cleaup(self, tmp_dir):
        gt_labels_dir = tmp_dir / "gt_labels"
        pred_labels_dir = tmp_dir / "pred_labels"

        if gt_labels_dir.exists():
            for file in gt_labels_dir.glob('*'):
                file.unlink()
            gt_labels_dir.rmdir()

        if pred_labels_dir.exists():
            for file in pred_labels_dir.glob('*'):
                file.unlink()
            pred_labels_dir.rmdir()

        if tmp_dir.exists():
            tmp_dir.rmdir()


    def compute_from_shapefiles(self,
                                gt_shp: Path | str,
                                pred_shp: Path | str,
                                *,
                                iou_threshold: float = 0.5):
        """
        Compute confusion matrix directly from shapefiles without intermediate YOLO text files.

        Each geometry's axis-aligned bounding box is extracted and matched using the same
        IoU logic as compute_confusion_matrix. Results are identical to the old implementation
        because tiles do not overlap geographically, so cross-tile IoU is always 0 and the
        per-tile grouping used previously has no effect on the final counts.

        Args:
            gt_shp: Path to the ground truth shapefile.
            pred_shp: Path to the predicted shapefile.
            reference_tif_dir: No longer required. Kept for backward compatibility.
            iou_threshold: IoU threshold for matching boxes (default=0.5).
            cleanup: No longer required. Kept for backward compatibility.

        Return:
            ConfusionMatrix: The computed confusion matrix.
        """
        try:
            import geopandas as gpd
        except ImportError:
            raise ImportError(
                "geopandas is required for direct shapefile computation. "
                "Install it with: pip install geopandas"
            )

        gt_gdf: GeoDataFrame = gpd.read_file(gt_shp)
        pred_gdf: GeoDataFrame = gpd.read_file(pred_shp)

        # Ensure both layers share the same coordinate reference system.
        if pred_gdf.crs != gt_gdf.crs:
            pred_gdf = pred_gdf.to_crs(gt_gdf.crs)

        def _geom_to_box(geom):
            """
            Convert a shapely geometry to the 8-coordinate segmentation format
            (x1,y1, x2,y2, x3,y3, x4,y4) expected by __calculate_iou.
            The axis-aligned bounding box corners are used, matching what the
            YOLO segmentation parser effectively computes when it calls min/max
            on the parsed coordinates.
            """
            minx, miny, maxx, maxy = geom.bounds
            return (minx, miny, maxx, miny, maxx, maxy, minx, maxy)

        gt_boxes = [
            _geom_to_box(geom)
            for geom in gt_gdf.geometry
            if geom is not None and not geom.is_empty
        ]
        pred_boxes = [
            _geom_to_box(geom)
            for geom in pred_gdf.geometry
            if geom is not None and not geom.is_empty
        ]

        total = ConfusionMatrix()

        if len(gt_boxes) == 0 and len(pred_boxes) == 0:
            return total

        total.tp, total.fp, total.fn = self.__match_boxes(gt_boxes, pred_boxes, iou_threshold)

        return total


if __name__ == "__main__":
    # Example: Specify your directories
    # cwd = Path.cwd()
    # ground_truth_dir = cwd / "shapefiles/ground_truth"
    # predictions_dir = cwd / "shapefiles/labels"
    # iou_threshold = 0.1

    # print("Computing confusion matrix...")
    # print(f"Ground truth directory: {ground_truth_dir}")
    # print(f"Predictions directory: {predictions_dir}")
    # print(f"IoU threshold: {iou_threshold}")

    # metrics = Metrics()
    # results = metrics.compute_confusion_matrix(ground_truth_dir, predictions_dir, iou_threshold)

    # home = Path.home()
    # gt_shp = home / "SDU/MasterThesis/OpenCV/shapefiles/BV_TF2_small.shp"
    # pred_shp = home / "SDU/MasterThesis/OpenCV/shapefiles/labels_shapefile.shp"
    # reference_tif_dir = home / "SDU/MasterThesis/OpenCV/splits"

    # metrics = Metrics()
    # results = metrics.compute_from_shapefiles(gt_shp, pred_shp, reference_tif_dir)

    home = Path.home()
    paths = [
        home / "SDU/MasterThesis/OpenCV/output_NGRDI_mask/big",
        home / "SDU/MasterThesis/OpenCV/output_NGRDI_mask/mid",
        home / "SDU/MasterThesis/OpenCV/output_NGRDI_mask/small",
    ]

    for pth in paths:
        results = ConfusionMatrix.fromFile(pth / "confusion_matrix.txt")

        results.print()
        results.plot(hold=True, save = pth / "confusion_matrix.png")
        results.plot(normalised=True, save = pth / "confusion_matrix_normalised.png")
